set -g prefix C-b
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
bind s splitw -v -c '#{pane_current_path}'
bind v splitw -h -c '#{pane_current_path}'
setw -g mode-keys vi
# bind move among windows like vim
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r ^k resizep -U 5
bind -r ^j resizep -D 5
bind -r ^h resizep -L 5
bind -r ^l resizep -R 5

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind p paste-buffer

set -g base-index 1
set -g pane-base-index 1
set -s focus-events on 
set-window-option -g automatic-rename on
set-window-option -g monitor-activity on

set -g status-left "🐶 #W" 
# for yazi compatibility
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
